name: covtobed
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest  # Updated from ubuntu-18.04
    
    steps:
      # Install required dependencies for Ubuntu
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Install current versions of compilers and bamtools
          sudo apt-get install -y clang g++ libbamtools-dev
      
      # Checkout the repository code
      - uses: actions/checkout@v4  # Updated from v2
      
      # Set compiler versions using proper environment variable syntax
      - name: Configure compilers
        run: |
          # Set GCC as default if CXX is g++
          if [ "$CXX" = "g++" ]; then
            echo "CXX=g++" >> $GITHUB_ENV
          fi
          # Set Clang as default if CXX is clang++
          if [ "$CXX" = "clang++" ]; then
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
      
      # Build the covtobed executable
      - name: Build covtobed
        run: |
          g++ -std=c++11 *.cpp \
            -I/usr/include/bamtools \
            /usr/lib/x86_64-linux-gnu/libbamtools.a \
            -o covtobed -lz
      
      # Test the built executable
      - name: Test help output
        run: ./covtobed -h
      
      - name: Test basic functionality
        run: ./covtobed test/demo.bam > /dev/null
      
      - name: Test physical coverage
        run: ./covtobed --physical-coverage test/mp.bam > /dev/null
      
      - name: Run test suite
        run: bash test/test.sh
